"""add field descr to categories

Revision ID: fc1adfef228c
Revises: 3aec3cce6ce0
Create Date: 2022-06-10 12:05:14.916218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc1adfef228c'
down_revision = '3aec3cce6ce0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('descr', sa.VARCHAR(length=140),
                                          nullable=False, server_default='description'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'descr')
    # ### end Alembic commands ###
